const SEND_EMAIL = "forevermoneer@gmail.com";

//on successful API call to generate token, inserts token into input box on page for later use
const onGetTokenSuccess = data => {
  $("#token").val(data.access_token);
};

//requests auth token from SFMC
const getToken = () => {
  $.ajax({
    type: "POST",
    url:
      "https://mc5wp718bxk52f6jvhyftb9-p5ny.auth.marketingcloudapis.com/v2/token",
    contentType: "application/x-www-form-urlencoded",
    data: {
      client_id: "b6rcpcja5cg9owbd0lfkz586",
      client_secret: "VUyGGv6Ta5yMLfvLNM2lPJCm",
      grant_type: "client_credentials"
    },
    success: onGetTokenSuccess,
    error: function(error) {
      console.log(error.responseJSON);
    }
  });
};

//general success function to use in API calls to display results
const onSuccess = data => console.log(data);

//general function to send emails, takes in the data (payload), trigger external key (to insert into url), and token generated by previous call
const sendEmail = (data, key, token) => {
  $.ajax({
    type: "POST",
    url: `https://mc5wp718bxk52f6jvhyftb9-p5ny.rest.marketingcloudapis.com/messaging/v1/messageDefinitionSends/key:${key}/send/`,
    contentType: "application/x-www-form-urlencoded",
    headers: {
      Authorization: "Bearer " + token
    },
    data: data,
    success: onSuccess,
    error: function(error) {
      console.log(error.responseJSON);
    }
  });
};

//functions for each email, creates data object, and passes in details to sendEmail function

// PASSWORD RESET
const sendPasswordReset = () => {
  let data = {
    To: {
      Address: SEND_EMAIL,
      SubscriberKey: SEND_EMAIL,
      ContactAttributes: {
        SubscriberAttributes: {
          EmailAddress: SEND_EMAIL,
          XML_DATA:
            "<USER><FIRSTNAME>kevena </FIRSTNAME><RESETPASSWORDURL>https://www.forever21.com/us/shop/Account/ResetPassword?id=8DcYrBYfRboBx39ENkrTo2HN/YAq+bnr&amp;str=pfoPUCroN+tln21mIgjhhPYukURj6/XE7SGz8yb6X6ix5wjbBFDzHqUt3F93SgbIf+ExOnTPkjAyh4W/XxDRiBgOTfnoo4s0MwW1NQJyh2M=</RESETPASSWORDURL><EMAIL>kmzachery@gmail.com</EMAIL></USER>"
        }
      }
    }
  };

  let token = $("#token").val();
  sendEmail(data, "PASSWORD_RESET", token);
};

// SHIPPING NOTIFICATION
const sendShipping = () => {
  let email = "michael.o@forever21.com";
  let data = {
    To: {
      Address: SEND_EMAIL,
      SubscriberKey: SEND_EMAIL,
      ContactAttributes: {
        SubscriberAttributes: {
          EmailAddress: SEND_EMAIL,
          XML_DATA:
            "<ORDER><BILLINGADDRESS><CUSTOMERNAME>Amanda Brau</CUSTOMERNAME><ADDRESS1>6765 East 135th Avenue</ADDRESS1><ADDRESS2></ADDRESS2><CITY>Thornton</CITY><STATE>CO</STATE><ZIPCODE>80602</ZIPCODE><PAYMETHOD>CC-4890</PAYMETHOD></BILLINGADDRESS><SHIPPINGINFORMATION><TRACKINGNUMBER>D10011444403597</TRACKINGNUMBER><SHIPDATE>12/31/18</SHIPDATE><TRACKINGURL>https://forever21.narvar.com/tracking/forever21/ontrac?tracking_numbers=D10011444403597&amp;order_number=84514950&amp;ozip=90031&amp;dzip=80602&amp;service=ST</TRACKINGURL><TRACKINGURLOFCARRIER>https://www.ontrac.com/trackingres.asp?tracking_number=D10011444403597</TRACKINGURLOFCARRIER><SHIPPINGMETHOD>Standard</SHIPPINGMETHOD><CUSTOMERNAME>Amanda Brau</CUSTOMERNAME><ADDRESS1>6765 East 135th Avenue</ADDRESS1><ADDRESS2></ADDRESS2><CITY>Thornton</CITY><STATE>CO</STATE><ZIPCODE>80602</ZIPCODE></SHIPPINGINFORMATION><ORDERNUMBER>84514950</ORDERNUMBER><ORDERDATE>12/30/2018 17:11:02</ORDERDATE><EMAIL>kkitka@salesforce.com</EMAIL><SUBTOTAL>90.20</SUBTOTAL><SHIPPINGTOTAL>0.00</SHIPPINGTOTAL><TAX>2.62</TAX><TOTAL>92.82</TOTAL><ITEMS><ITEM><PRODIMAGE>http://www.forever21.com/images/intl_g/00327653-01.jpg</PRODIMAGE><NAME>Striped-Trim Marled Shorts</NAME><PRODUCTID>2000327653</PRODUCTID><SIZECOLOR>GREY/MULTI</SIZECOLOR><QUANTITY>1</QUANTITY><EXTENDEDPRICE>9.90</EXTENDEDPRICE><OOS></OOS></ITEM><ITEM><PRODIMAGE>http://www.forever21.com/images/intl_g/00327651-01.jpg</PRODIMAGE><NAME>Striped-Trim Pajama Top</NAME><PRODUCTID>2000327651</PRODUCTID><SIZECOLOR>GREY/MULTI</SIZECOLOR><QUANTITY>1</QUANTITY><EXTENDEDPRICE>14.90</EXTENDEDPRICE><OOS></OOS></ITEM><ITEM><PRODIMAGE>http://www.forever21.com/images/intl_g/00350395-01.jpg</PRODIMAGE><NAME>Heart Print Wrap Maxi Dress</NAME><PRODUCTID>2000350395</PRODUCTID><SIZECOLOR>BLACK/RED</SIZECOLOR><QUANTITY>1</QUANTITY><EXTENDEDPRICE>38.00</EXTENDEDPRICE><OOS></OOS></ITEM><ITEM><PRODIMAGE>http://www.forever21.com/images/intl_g/00345793-01.jpg</PRODIMAGE><NAME>Hooded Maxi Dress</NAME><PRODUCTID>2000345793</PRODUCTID><SIZECOLOR>HEATHER GREY</SIZECOLOR><QUANTITY>1</QUANTITY><EXTENDEDPRICE>17.50</EXTENDEDPRICE><OOS></OOS></ITEM><ITEM><PRODIMAGE>http://www.forever21.com/images/intl_g/00284077-05.jpg</PRODIMAGE><NAME>Faux Leather Slide Sandals</NAME><PRODUCTID>2000284077</PRODUCTID><SIZECOLOR>WHITE</SIZECOLOR><QUANTITY>1</QUANTITY><EXTENDEDPRICE>9.90</EXTENDEDPRICE><OOS></OOS></ITEM></ITEMS></ORDER>"
        }
      }
    }
  };

  let token = $("#token").val();
  sendEmail(data, "SHIPPING_NOTIFICATION", token);
};

// COMING SOON CONFIRMATION
const comingSoonConfirmation = () => {
  let email = "michael.o@forever21.com";
  let data = {
    To: {
      Address: SEND_EMAIL,
      SubscriberKey: SEND_EMAIL,
      ContactAttributes: {
        SubscriberAttributes: {
          EmailAddress: SEND_EMAIL,
          XML_DATA:
            "<ORDER><BILLINGADDRESS><CUSTOMERNAME>Amanda Brau</CUSTOMERNAME><ADDRESS1>6765 East 135th Avenue</ADDRESS1><ADDRESS2></ADDRESS2><CITY>Thornton</CITY><STATE>CO</STATE><ZIPCODE>80602</ZIPCODE><PAYMETHOD>CC-4890</PAYMETHOD></BILLINGADDRESS><SHIPPINGINFORMATION><TRACKINGNUMBER>D10011444403597</TRACKINGNUMBER><SHIPDATE>12/31/18</SHIPDATE><TRACKINGURL>https://forever21.narvar.com/tracking/forever21/ontrac?tracking_numbers=D10011444403597&amp;order_number=84514950&amp;ozip=90031&amp;dzip=80602&amp;service=ST</TRACKINGURL><TRACKINGURLOFCARRIER>https://www.ontrac.com/trackingres.asp?tracking_number=D10011444403597</TRACKINGURLOFCARRIER><SHIPPINGMETHOD>Standard</SHIPPINGMETHOD><CUSTOMERNAME>Amanda Brau</CUSTOMERNAME><ADDRESS1>6765 East 135th Avenue</ADDRESS1><ADDRESS2></ADDRESS2><CITY>Thornton</CITY><STATE>CO</STATE><ZIPCODE>80602</ZIPCODE></SHIPPINGINFORMATION><ORDERNUMBER>84514950</ORDERNUMBER><ORDERDATE>12/30/2018 17:11:02</ORDERDATE><EMAIL>kkitka@salesforce.com</EMAIL><SUBTOTAL>90.20</SUBTOTAL><SHIPPINGTOTAL>0.00</SHIPPINGTOTAL><TAX>2.62</TAX><TOTAL>92.82</TOTAL><ITEMS><ITEM><PRODIMAGE>http://www.forever21.com/images/intl_g/00327653-01.jpg</PRODIMAGE><NAME>Striped-Trim Marled Shorts</NAME><PRODUCTID>2000327653</PRODUCTID><SIZECOLOR>GREY/MULTI</SIZECOLOR><QUANTITY>1</QUANTITY><EXTENDEDPRICE>9.90</EXTENDEDPRICE><OOS></OOS></ITEM><ITEM><PRODIMAGE>http://www.forever21.com/images/intl_g/00327651-01.jpg</PRODIMAGE><NAME>Striped-Trim Pajama Top</NAME><PRODUCTID>2000327651</PRODUCTID><SIZECOLOR>GREY/MULTI</SIZECOLOR><QUANTITY>1</QUANTITY><EXTENDEDPRICE>14.90</EXTENDEDPRICE><OOS></OOS></ITEM><ITEM><PRODIMAGE>http://www.forever21.com/images/intl_g/00350395-01.jpg</PRODIMAGE><NAME>Heart Print Wrap Maxi Dress</NAME><PRODUCTID>2000350395</PRODUCTID><SIZECOLOR>BLACK/RED</SIZECOLOR><QUANTITY>1</QUANTITY><EXTENDEDPRICE>38.00</EXTENDEDPRICE><OOS></OOS></ITEM><ITEM><PRODIMAGE>http://www.forever21.com/images/intl_g/00345793-01.jpg</PRODIMAGE><NAME>Hooded Maxi Dress</NAME><PRODUCTID>2000345793</PRODUCTID><SIZECOLOR>HEATHER GREY</SIZECOLOR><QUANTITY>1</QUANTITY><EXTENDEDPRICE>17.50</EXTENDEDPRICE><OOS></OOS></ITEM><ITEM><PRODIMAGE>http://www.forever21.com/images/intl_g/00284077-05.jpg</PRODIMAGE><NAME>Faux Leather Slide Sandals</NAME><PRODUCTID>2000284077</PRODUCTID><SIZECOLOR>WHITE</SIZECOLOR><QUANTITY>1</QUANTITY><EXTENDEDPRICE>9.90</EXTENDEDPRICE><OOS></OOS></ITEM></ITEMS></ORDER>"
        }
      }
    }
  };

  let token = $("#token").val();
  sendEmail(data, "COMING_SOON_CONFIRMATION", token);
};

// ORDER CONFIRMATION
const sendOrder = () => {
  let data = {
    To: {
      Address: SEND_EMAIL,
      SubscriberKey: SEND_EMAIL,
      ContactAttributes: {
        SubscriberAttributes: {
          EmailAddress: SEND_EMAIL,
          XML_DATA:
            "<ORDER><BILLINGADDRESS><CUSTOMERNAME>Eric Pointer</CUSTOMERNAME><ADDRESS1>505 6TH ST SW</ADDRESS1><ADDRESS2>APT 29G</ADDRESS2><CITY>ROANOKE</CITY><STATE>VA</STATE><ZIPCODE>24016</ZIPCODE><PAYMETHOD>CC-4890</PAYMETHOD></BILLINGADDRESS><SHIPPINGINFORMATION><SHIPPINGMETHOD>Standard Shipping</SHIPPINGMETHOD><CUSTOMERNAME>Eric Pointer</CUSTOMERNAME><ADDRESS1>505 6TH ST SW</ADDRESS1><ADDRESS2>APT 29G</ADDRESS2><CITY>ROANOKE</CITY><STATE>VA</STATE><ZIPCODE>24016</ZIPCODE></SHIPPINGINFORMATION><ORDERNUMBER>83237967</ORDERNUMBER><ORDERDATE>11/26/2018 00:00:16</ORDERDATE><SUBTOTAL>37.12</SUBTOTAL><SHIPPINGTOTAL>0.00</SHIPPINGTOTAL><TAX>1.97</TAX><TOTAL>39.09</TOTAL><EMAIL>kkitka@salesforce.com</EMAIL><USERUID>622A43FF-85BB-4F1D-9D88-8AD58F4586C9</USERUID><PAYMENT><GIFTCARDTOTALAMOUNT>0.00</GIFTCARDTOTALAMOUNT><CREDITCARDTOTALAMOUNT>39.09</CREDITCARDTOTALAMOUNT><PAYPALTOTALAMOUNT>0.00</PAYPALTOTALAMOUNT></PAYMENT><ITEMS><ITEM><PRODIMAGE>http://www.forever21.com/images/intl_g/00342056-01.jpg</PRODIMAGE><NAME>Embroidered Polka Dot Dress</NAME><PRODUCTID>2000342056012</PRODUCTID><SIZECOLOR>SMALL,IVORY/BLACK</SIZECOLOR><QUANTITY>1</QUANTITY><EXTENDEDPRICE>22.90</EXTENDEDPRICE></ITEM><ITEM><PRODIMAGE>http://www.forever21.com/images/intl_g/00348483-03.jpg</PRODIMAGE><NAME>Floral Button-Front Fit &amp; Flare Dress</NAME><PRODUCTID>2000348483032</PRODUCTID><SIZECOLOR>SMALL,IVORY/PINK</SIZECOLOR><QUANTITY>1</QUANTITY><EXTENDEDPRICE>17.90</EXTENDEDPRICE></ITEM><ITEM><PRODIMAGE>http://www.forever21.com/images/intl_g/00366277-01.jpg</PRODIMAGE><NAME>Ditsy Floral Mini Dress</NAME><PRODUCTID>2000366277012</PRODUCTID><SIZECOLOR>SMALL,BLACK/MULTI</SIZECOLOR><QUANTITY>1</QUANTITY><EXTENDEDPRICE>24.90</EXTENDEDPRICE></ITEM></ITEMS></ORDER>"
        }
      }
    }
  };

  let token = $("#token").val();
  sendEmail(data, "ORDER_CONFIRMATION", token);
};

// GENERAL TRANSACTION
const sendGeneral = () => {
  let data = {
    To: {
      Address: SEND_EMAIL,
      SubscriberKey: SEND_EMAIL,
      ContactAttributes: {
        SubscriberAttributes: {
          EmailAddress: SEND_EMAIL,
          XML_DATA:
            "<GENERAL> <EMAILSUBJECT> Forever21 Order Cancellation Notification - [85490047] </EMAILSUBJECT> <EMAILTITLE> Order Cancellation </EMAILTITLE> <EMAILCONTENT> <![CDATA[Dear Customer, <br><br>Your request to cancel your order has been approved.<br>Any pending authorizations reflected in your account should void within 24 hours, but may vary depending on your financial institution or credit card company.<br><br>]]> </EMAILCONTENT> </GENERAL>"
        }
      }
    }
  };

  let token = $("#token").val();
  sendEmail(data, "GENERAL_TRANSACTION", token);
};

//init function wiring up buttons with jQuery
const init = () => {
  $("#getToken").on("click", getToken);
  $("#pwReset").on("click", sendPasswordReset);
  $("#shipping").on("click", sendShipping);
  $("#order").on("click", sendOrder);
  $("#general").on("click", sendGeneral);
  $("#csConfirmation").on("click", comingSoonConfirmation);
};

$(document).ready(() => {
  init();
});
